CREATE TABLE [dbo].[User]
(
    [Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
    [Email] NVARCHAR(320) NOT NULL,
    [FirstName] NVARCHAR(256) NULL,
    [MiddleName] NVARCHAR(256) NULL,
    [LastName] NVARCHAR(256) NULL,
    [Username] NVARCHAR(256) NOT NULL,
    [Password] VARBINARY(512) NOT NULL,
    [Salt] VARBINARY(512) NOT NULL,
    [Level] INT DEFAULT 0 NOT NULL,
    [Score] INT DEFAULT 0 NOT NULL,
    [IsAdmin] BIT DEFAULT 0 NOT NULL,
    [IsBanned] BIT DEFAULT 0 NOT NULL,
    [BannedUntil] DATETIMEOFFSET NULL,
    [CreatedAt] DATETIMEOFFSET NOT NULL,
    [UpdatedAt] DATETIMEOFFSET NOT NULL,
    [IsDeleted] BIT DEFAULT 0 NOT NULL,
    [IsTwoFactorEnabled] BIT DEFAULT 0 NOT NULL,
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC)
);